# app-pods.yaml
apiVersion: v1
kind: Pod
metadata:
  name: crud-pod
  labels:
    app: crud
spec:
  containers:
    - name: crud-service
      image: jriosv/redbicicletas-crud
      ports:
        - containerPort: 5000
    - name: mongo-crud
      image: mongo
      ports:
        - containerPort: 27017


---

apiVersion: v1
kind: Service
metadata:
  name: crud-service
spec:
  selector:
    app: crud
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort



