# app-pods.yaml
apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: jriosv/redbicicletas-frontend
      env:
      - name: CRUD_URI
        value: "http://crud-service:5000/api/"
      - name: MAP_URI
        value: "http://map-service:8000/api/"
      - name: AJAX_URI
        value: "http://map-service:8000/api/ubicacion"
      ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort



