# app-pods.yaml
apiVersion: v1
kind: Pod
metadata:
  name: map-pod
  labels:
    app: map-app
spec:
  containers:
    - name: map-service
      image: jriosv/redbicicletas-map
      env:
      - name: MONGO_URI
        value: "mongodb://localhost:27017"
      ports:
        - containerPort: 8000
    - name: mongo-map
      image: mongo
      ports:
        - containerPort: 27017


---

apiVersion: v1
kind: Service
metadata:
  name: map-service
spec:
  selector:
    app: map-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort