FROM node:12-alpine3.10
# Create app directory
RUN mkdir /app
WORKDIR /app

RUN apk update
RUN apk add --no-cache tzdata
ENV TZ=America/Bogota
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json /app/

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . /app

ENV NODE_ENV QA

ENV CLIENT_ID  "1002985450292-dgq7n1gmo12l81ufbbaqspcn1id9cqfm.apps.googleusercontent.com"
ENV PORT 3000

EXPOSE 3000

CMD [ "npm", "start" ]


